### ISSUE TITLE
Ruby capstone project

### ISSUE THREAD

**Issue by basem909** [kinginthenorthcodez/catalog-of-my-things-app#47]
We are 4 person group @Amedzro-Elikplim @kinginthenorthcodez @basem909 
@basem909 is assigned to team member 1 
@Amedzro-Elikplim  is assigned to team member 2
@kinginthenorthcodez  is assigned to team member 3 
@Gedewon  is assigned to team member 4 
[a link to the project](https://github.com/kinginthenorthcodez/catalog-of-my-things-app/projects/1)

**Comment by tresorsawasawa** [comment]
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @**Team**, 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required changes :recycle: :recycle: 
- [ ] Kindly make sure the GitHub project link you provided in the above issue is for your **Kanboard project** and not for the GitHub repo as required for this project. 
- [ ] Kindly make sure all your cards are assigned to team members. Right now, I just noticed that there are some of them which are not assigned yet(especially for the #Team_member_4).
- [ ] As you decided to assign all **group tasks** to everyone in your group, I suggest you also add the **fourth** team member to group tasks so all tasks are distributed in a fair way.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gedewon** [comment]
Thank you!! , we updated the issue above.

**Comment by aimemalaika** [comment]
Hi Team, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
